sudo: required
dist: trusty

language: php
php:
	- 7.1.9

cache: yarn

addons:
	chrome: stable

services:
	- mysql

before_install:
	- mysql -e 'CREATE DATABASE `ehosp-services`;'
	- cd src

install:
	- mv .env.example .env
	- travis_retry composer install --no-interaction --prefer-dist --no-suggest
	- yarn install
	- php artisan key:generate
	- php artisan voyager:install

before_script:
	- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
	- chmod +x ./cc-test-reporter
	- ./cc-test-reporter before-build
	- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
	- php artisan serve &

script:
	- npm run prod
	- php artisan dusk
	- phpunit --coverage-clover build/logs/clover.xml

after_script:
	- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT