sudo: required
dist: trusty

language: php
php:
  - 7.1.9

addons:
   chrome: stable

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE ehosp-services;'

install:
   - mv .env.example .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest
   - php artisan key:generate
   - php artisan db:seed

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php artisan serve &

script:
   - php artisan dusk
   - phpunit